### ISSUE TITLE
Create Skeleton Flask App for "Update Tags".

### ISSUE THREAD

**Issue by nzwan** [aaronbolyard-school/CSC-289#26]

**Comment by aaronbolyard-school** [comment]
I suggest creating a "AddTagForm" (under forms directory) with a "tag" field and submit button. Then add this form using wtforms / flask_bootstrap to the view_single template. Update the single_view route in `photomanager/views/view.py` to accept POST methods and process the form.

I added `tag_photo` and `untag_photo` to the photo controller that handles adding and removing tags.
